# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9d18f8d858c0b8c9a50fd50925e08aececf140614db5ff7d0bd22d922071e80093f7515e17d7fafa2c808c270fa0686030e4c32422515999b3cf18bc4bfd36d

test:
  secret_key_base: 5a8296aa8a9ab17a6ceffbc5777c8d337f5cd7dd93d4a3ab03130a39450adb72aeafe536d83e11ee8c375cfdbf9c5aee93a1f322b6c19fc33c8d8ce404556e60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
